---
- hosts: all
  sudo: yes
  remote_user: vagrant
  vars:
    - rbenv_root: ~/.rbenv
    - ruby_version: 2.3.0

  tasks:
    - apt_repository: 
        repo: 'ppa:brightbox/ruby-ng'
        update_cache: yes

    - name: update and upgrade apt packages
      apt: 
        update_cache: yes 

    - name: Add Nginx Repository
      apt_repository: repo='ppa:nginx/stable' state=present
      register: ppainstalled

    - name: Install Nginx
      apt: pkg=nginx state=latest update_cache=true
      when: ppainstalled|success
      notify:
      - Start Nginx

    - name: Add .ssh file to root directory
      shell: touch ~/.ssh

    - name: Install ruby
      apt: 
        name: ruby2.3

    - name: Install ruby-dev
      apt:
        name: ruby2.3-dev

    - name: Install Postgres
      apt: pkg=postgresql state=latest update_cache=true

    - name: rubygems | install bundler
      shell: gem install bundler

    - name: buiild essential install
      apt:
        name: build-essential
        update_cache: yes 

    - name: libxml poop
      apt:
        name: libxslt-dev
        state: latest
        update_cache: yes  

    - name: install libxml because nokogiri is poop
      apt:
        name: libxml2-dev 
        state: latest
        update_cache: yes 

    - name: zlib install
      apt:
        name: zlib1g-dev
        state: latest
        update_cache: yes

    - name: rubygems | install rails
      shell: gem install rails

  handlers:
     - name: Start Nginx
       service: name=nginx state=started